### 1.User Register API
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "email": "testemail@gmail.com",
    "password": "react"
}

### 2. User Login API
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email": "testemail@gmail.com",
    "password": "react"
}
### 3. User auth API
GET http://localhost:3000/api/v1/authenticate
authorization : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk4NDAyNDk0fQ.0F8nI1NMRrC-M8z-8u_3JV24Y0qWsfMuKSHzHpBMm2Y"