### 1.User Register API
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "email": "testemail@gmail.com",
    "password": "react"
}

### 2. User Login API
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email": "testemail@gmail.com",
    "password": "react"
}
### 3. User Logout API